export {
  SOCIAL_PUBLISHING_PLUGIN_ID,
  SOCIAL_PUBLISHING_RUNTIME,
  SOCIAL_PUBLISH_QUEUE_NAME,
  SocialPublishingGateError,
  SocialPublishingInputError,
  appendContentItemMedia,
  completeSocialOAuth,
  createQueuedContentPublicationAndEnqueue,
  createQueuedSocialVariantPublicationAndEnqueue,
  disconnectSocialPublishingAccount,
  createContentItem,
  getSocialContentPackage,
  deleteContentItem,
  dispatchDueSocialPublications,
  getContentStats,
  getSocialPublishingRuntimeStatus,
  listContentItems,
  listSocialProviderSettings,
  listSocialContentPackages,
  listSocialPublishingAccounts,
  markContentItemPublishing,
  processSocialPublishBatch,
  publishQueuedContentPublication,
  queueContentItem,
  reorderContentQueue,
  startSocialOAuth,
  unqueueContentItem,
  updateSocialProviderSettings,
  updateSocialAccountVariant,
  updateContentItem,
  SocialContentPackageInputError,
  type SocialContentPackageDetail,
  type UpdateSocialAccountVariantInput,
  type SocialPublishQueueMessage,
  type SocialVariantPublication,
} from "@me3-core/plugin-social-publishing";
