/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'unplugin-vue-router/types'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/login': RouteRecordInfo<'/login', '/', Record<never, never>, Record<never, never>>,
    '/[...path]': RouteRecordInfo<'/[...path]', '/:path(.*)', { path: ParamValue<true> }, { path: ParamValue<false> }>,
    '/account': RouteRecordInfo<'/account', '/account', Record<never, never>, Record<never, never>>,
    '/accounts': RouteRecordInfo<'/accounts', '/accounts', Record<never, never>, Record<never, never>>,
    '/assistant/': RouteRecordInfo<'/assistant/', '/assistant', Record<never, never>, Record<never, never>>,
    '/calendar': RouteRecordInfo<'/calendar', '/calendar', Record<never, never>, Record<never, never>>,
    '/contacts': RouteRecordInfo<'/contacts', '/contacts', Record<never, never>, Record<never, never>>,
    '/create': RouteRecordInfo<'/create', '/create', Record<never, never>, Record<never, never>>,
    '/email': RouteRecordInfo<'/email', '/email', Record<never, never>, Record<never, never>>,
    '/journal': RouteRecordInfo<'/journal', '/journal', Record<never, never>, Record<never, never>>,
    '/mission-control': RouteRecordInfo<'/mission-control', '/mission-control', Record<never, never>, Record<never, never>>,
    '/mission-control-projects': RouteRecordInfo<'/mission-control-projects', '/mission-control/projects', Record<never, never>, Record<never, never>>,
    '/mission-control-wheel-of-life': RouteRecordInfo<'/mission-control-wheel-of-life', '/mission-control/wheel-of-life', Record<never, never>, Record<never, never>>,
    '/sites/[username]': RouteRecordInfo<'/sites/[username]', '/sites/:username', { username: ParamValue<true> }, { username: ParamValue<false> }>,
    '/sites/[username]/build': RouteRecordInfo<'/sites/[username]/build', '/sites/:username/build', { username: ParamValue<true> }, { username: ParamValue<false> }>,
    '/sites/[username]/landing-pages/new': RouteRecordInfo<'/sites/[username]/landing-pages/new', '/sites/:username/landing-pages/new', { username: ParamValue<true> }, { username: ParamValue<false> }>,
    '/social': RouteRecordInfo<'/social', '/social', Record<never, never>, Record<never, never>>,
    '/start': RouteRecordInfo<'/start', '/start', Record<never, never>, Record<never, never>>,
  }
}
