import { existsSync } from "node:fs";
import { mkdir, readFile, writeFile } from "node:fs/promises";
import path from "node:path";

export const DEFAULT_TEMPLATE_CONFIG = "wrangler.toml";
export const DEFAULT_INSTALL_MANIFEST = ".me3/install.json";
export const DEFAULT_GENERATED_CONFIG = ".wrangler/me3.generated.toml";
export const D1_PLACEHOLDER = "replace-with-generated-d1-id";

export async function prepareDeployConfig(options = {}) {
  const rootDir = options.rootDir || process.cwd();
  const templateConfigPath = resolveFromRoot(rootDir, options.templateConfig || DEFAULT_TEMPLATE_CONFIG);
  const manifestPath = resolveFromRoot(rootDir, options.manifest || DEFAULT_INSTALL_MANIFEST);
  const outputPath = resolveFromRoot(rootDir, options.output || DEFAULT_GENERATED_CONFIG);

  if (!existsSync(templateConfigPath)) {
    throw new Error(`Could not find ${relativeToRoot(rootDir, templateConfigPath)}.`);
  }

  const manifest = await readInstallManifest(manifestPath);
  if (!manifest) {
    return {
      configPath: templateConfigPath,
      configPathRelative: relativeToRoot(rootDir, templateConfigPath),
      generated: false,
      manifestPath,
      manifestPathRelative: relativeToRoot(rootDir, manifestPath),
      manifest: null,
    };
  }

  const template = await readFile(templateConfigPath, "utf8");
  const config = buildDeployConfig(template, manifest);
  await mkdir(path.dirname(outputPath), { recursive: true });
  await writeFile(
    outputPath,
    [
      "# Generated by scripts/prepare-deploy-config.mjs.",
      "# Do not edit this file. Update .me3/install.json or wrangler.toml instead.",
      "",
      config.trimEnd(),
      "",
    ].join("\n"),
    "utf8",
  );

  return {
    configPath: outputPath,
    configPathRelative: relativeToRoot(rootDir, outputPath),
    generated: true,
    manifestPath,
    manifestPathRelative: relativeToRoot(rootDir, manifestPath),
    manifest,
  };
}

export async function readInstallManifest(manifestPath) {
  if (!existsSync(manifestPath)) return null;
  const raw = await readFile(manifestPath, "utf8");
  const manifest = JSON.parse(raw);
  validateInstallManifest(manifest, manifestPath);
  return manifest;
}

export function buildDeployConfig(template, manifest) {
  let config = template;
  const workerName = manifest.worker?.name;
  const d1 = manifest.d1 || {};
  const r2 = manifest.r2 || {};

  if (workerName) {
    config = setTopLevelTomlString(config, "name", workerName);
  }

  if (d1.databaseName || d1.databaseId) {
    config = setD1Config(config, {
      databaseName: d1.databaseName,
      databaseId: d1.databaseId,
    });
  }

  if (r2.bucketName) {
    config = setR2BucketName(config, r2.bucketName);
  }

  return config;
}

export function getD1Config(value) {
  const block = getTomlArrayBlock(value, "d1_databases", "DB");
  return {
    databaseId: block?.match(/database_id\s*=\s*"([^"]+)"/)?.[1] || "",
    databaseName: block?.match(/database_name\s*=\s*"([^"]+)"/)?.[1] || "",
  };
}

export function getR2BucketName(value) {
  const block = getTomlArrayBlock(value, "r2_buckets", "SITE_ASSETS");
  return block?.match(/bucket_name\s*=\s*"([^"]+)"/)?.[1] || "";
}

export function setD1Config(value, { databaseName, databaseId }) {
  const blockPattern =
    /\n\[\[d1_databases\]\]\n(?:(?!\n\[)[\s\S])*?binding\s*=\s*"DB"(?:(?!\n\[)[\s\S])*/;

  if (!blockPattern.test(value)) {
    throw new Error('Could not find a [[d1_databases]] block with binding = "DB".');
  }

  return value.replace(blockPattern, (block) => {
    let next = block;
    if (databaseName) next = setTomlString(next, "database_name", databaseName);
    if (databaseId) next = setTomlString(next, "database_id", databaseId);
    return next;
  });
}

export function setR2BucketName(value, bucketName) {
  const blockPattern =
    /\n\[\[r2_buckets\]\]\n(?:(?!\n\[)[\s\S])*?binding\s*=\s*"SITE_ASSETS"(?:(?!\n\[)[\s\S])*/;

  if (blockPattern.test(value)) {
    return value.replace(blockPattern, (block) => setTomlString(block, "bucket_name", bucketName));
  }

  const activeBlock = [
    "",
    "# Core file storage for site media and future plugin-owned files.",
    "[[r2_buckets]]",
    'binding = "SITE_ASSETS"',
    `bucket_name = "${bucketName}"`,
  ].join("\n");
  const assetsIndex = value.indexOf("\n[assets]");

  if (assetsIndex !== -1) {
    return `${value.slice(0, assetsIndex)}${activeBlock}\n${value.slice(assetsIndex)}`;
  }

  return `${value.trimEnd()}${activeBlock}\n`;
}

export function createInstallManifest(input) {
  return removeEmptyFields({
    schemaVersion: 1,
    worker: removeEmptyFields({
      name: input.workerName,
    }),
    d1: removeEmptyFields({
      binding: "DB",
      databaseName: input.databaseName,
      databaseId: input.databaseId,
      migrationsDir: "apps/worker/migrations",
    }),
    r2: removeEmptyFields({
      binding: "SITE_ASSETS",
      bucketName: input.bucketName,
    }),
    createdAt: input.createdAt,
    updatedAt: input.updatedAt,
  });
}

export async function writeInstallManifest(manifestPath, manifest) {
  await mkdir(path.dirname(manifestPath), { recursive: true });
  await writeFile(manifestPath, `${JSON.stringify(manifest, null, 2)}\n`, "utf8");
}

function validateInstallManifest(manifest, manifestPath) {
  if (!manifest || typeof manifest !== "object") {
    throw new Error(`${manifestPath} must contain a JSON object.`);
  }

  if (manifest.schemaVersion !== 1) {
    throw new Error(`${manifestPath} has an unsupported schemaVersion.`);
  }

  const workerName = manifest.worker?.name;
  const databaseName = manifest.d1?.databaseName;
  const databaseId = manifest.d1?.databaseId;
  const bucketName = manifest.r2?.bucketName;

  if (workerName && !isValidResourceName(workerName)) {
    throw new Error(`Invalid Worker name "${workerName}" in ${manifestPath}.`);
  }
  if (databaseName && !isValidResourceName(databaseName)) {
    throw new Error(`Invalid D1 database name "${databaseName}" in ${manifestPath}.`);
  }
  if (databaseId && !isValidDatabaseId(databaseId)) {
    throw new Error(`Invalid D1 database id "${databaseId}" in ${manifestPath}.`);
  }
  if (bucketName && !isValidResourceName(bucketName)) {
    throw new Error(`Invalid R2 bucket name "${bucketName}" in ${manifestPath}.`);
  }
}

function getTomlArrayBlock(value, blockName, binding) {
  return value.match(
    new RegExp(
      `\\n\\[\\[${blockName}\\]\\]\\n(?:(?!\\n\\[)[\\s\\S])*?binding\\s*=\\s*"${binding}"(?:(?!\\n\\[)[\\s\\S])*`,
    ),
  )?.[0];
}

function setTopLevelTomlString(value, key, nextValue) {
  const pattern = new RegExp(`^${key}\\s*=\\s*"[^"]*"`, "m");
  if (pattern.test(value)) {
    return value.replace(pattern, `${key} = "${nextValue}"`);
  }
  return `${key} = "${nextValue}"\n${value}`;
}

function setTomlString(block, key, value) {
  const pattern = new RegExp(`${key}\\s*=\\s*"[^"]*"`);
  if (pattern.test(block)) {
    return block.replace(pattern, `${key} = "${value}"`);
  }
  return `${block.trimEnd()}\n${key} = "${value}"\n`;
}

function removeEmptyFields(value) {
  if (!value || typeof value !== "object" || Array.isArray(value)) return value;
  return Object.fromEntries(
    Object.entries(value)
      .map(([key, entry]) => [key, removeEmptyFields(entry)])
      .filter(([, entry]) => {
        if (entry === undefined || entry === null || entry === "") return false;
        if (typeof entry === "object" && !Array.isArray(entry)) return Object.keys(entry).length > 0;
        return true;
      }),
  );
}

function resolveFromRoot(rootDir, value) {
  return path.isAbsolute(value) ? value : path.resolve(rootDir, value);
}

function relativeToRoot(rootDir, value) {
  return path.relative(rootDir, value) || ".";
}

export function isValidResourceName(value) {
  return /^[a-z0-9][a-z0-9-]{1,61}[a-z0-9]$/.test(value);
}

export function isValidDatabaseId(value) {
  return /^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$/i.test(value);
}
